services:
  postgres:
    image: postgres:16-alpine
    container_name: job-portal-db-local
    restart: always
    environment:
      POSTGRES_USER: nnnsns
      POSTGRES_PASSWORD: lkalkslakslajlsja
      POSTGRES_DB: job_portal
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d job_portal']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # --- REDIS ADDED HERE ---
  redis:
    image: redis:7-alpine
    container_name: job-portal-redis-local
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data_local:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_local:
  redis_data_local: # Added volume for Redis persistence
