services:
  postgres:
    image: postgres:16-alpine
    container_name: job-portal-db-master
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: job_portal
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d job_portal']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - job-portal-network

  mongo:
    image: mongo:latest
    container_name: job-portal-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lawahm303_db_user
      - MONGO_INITDB_ROOT_PASSWORD=FpReJpRhZq8BDx8n
      - MONGO_INITDB_DATABASE=job_portal
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - job-portal-network

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: job-portal-backend
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/src:/app/src
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:5000/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - job-portal-network

  frontend:
    build:
      context: ./client
      dockerfile: DockerFile
    container_name: job-portal-frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    env_file:
      - ./client/.env.local
    networks:
      - job-portal-network
    volumes:
      - ./client/src:/app/src

networks:
  job-portal-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
