services:
  postgres:
    image: postgres:16-alpine
    container_name: job-portal-db-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: job_portal
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d job_portal']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres_data_local:
